### ISSUE TITLE
async-hooks 文章疑問

### ISSUE THREAD

**Issue by s1hon** [vicanso/articles#6]
我終於發現 `async-hooks` 的範例程式碼中的 `als` 是指到另外一個套件
(原本有寄信給你，就直接忽略就可以了XD)

但是不知道為何你有使用 ` const end = als.get('timing').start('getUserInfo');` 以及 `end();`
有去翻了一下你的 `async-local-storage` 中好像也沒這用法？

https://github.com/vicanso/articles/blob/master/async-hooks/app.js#L91-L103

**Comment by vicanso** [comment]
使用到的timing是在前面的流程中设置的对象 (https://github.com/vicanso/supertiming)：

```js
// 接收请求，获取ID并设置X-Response-Id
app.use((ctx, next) => {
  const id = ctx.get('X-Request-Id') || shortid();
  ctx.set('X-Response-Id', id);
  als.set('id', id);
  als.set('timing', new Timing({
    precision: 'ms',
  }));
  return next();
});
```
